export enum ErrorCode {
  MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER",
  INVALID_TOKEN = "INVALID_TOKEN",
  EMAIL_DOMAIN_NOT_ALLOWED = "EMAIL_DOMAIN_NOT_ALLOWED",
  ADMIN_REQUIRED = "ADMIN_REQUIRED",
  ROLE_FORBIDDEN = "ROLE_FORBIDDEN",

  USER_NOT_FOUND = "USER_NOT_FOUND",
  ADMIN_GRANT_NOT_FOUND = "ADMIN_GRANT_NOT_FOUND",
  PROFILE_IMAGE_NOT_FOUND = "PROFILE_IMAGE_NOT_FOUND",
  INVALID_PROFILE_IMAGE = "INVALID_PROFILE_IMAGE",
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  GLOBAL_SETTINGS_NOT_FOUND = "GLOBAL_SETTINGS_NOT_FOUND",
  LAST_ADMIN_REMOVAL_FORBIDDEN = "LAST_ADMIN_REMOVAL_FORBIDDEN",

  REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",
  COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
  REVIEW_COMMIT_NOT_FOUND = "REVIEW_COMMIT_NOT_FOUND",
  INVALID_GITWEB_URL = "INVALID_GITWEB_URL",
  GITWEB_FETCH_FAILED = "GITWEB_FETCH_FAILED",
  GITWEB_PARSE_FAILED = "GITWEB_PARSE_FAILED",

  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
}
